### ISSUE TITLE
Fjerne openEHR-EHR-OBSERVATION.temperature.v1.adl? 

### ISSUE THREAD

**Issue by bjornna** [bjornna/dips-ckm#5]
Arketypen openEHR-EHR-OBSERVATION.temperature.v1.adl er tiltenkt bruk på temperatur av et spesifikt objekt og IKKE kroppstemperatur. 

This temperature is not to be used to record the body temperature, which is a surrogate for the whole body temperature of the subject - use OBSERVATION.body_temperature instead in this situation.

Det er viktig at disse ikke forveksles. Det har allerede skjedd og det er nok undertegnede som har tatt feil. 

Skal vi fjerne denne arketypen fra repositoriet og heller legge den til når vi får behov?

**Comment by AncaHeyd** [comment]
Enig. Det er veldig lett å forveksle disse og jeg tenker det er et godt forslag å fjerne eden ene fra vårt repository og heller ta den inn ved behov.

Ha en strålende dag
[cid:image001.png@01D0624B.BEB55B10]
Anca
Mobil +47 472 63 241

Fra: Bjørn Næss [mailto:notifications@github.com]
Sendt: torsdag 15. september 2016 17.27
Til: bjornna/dips-ckm <dips-ckm@noreply.github.com>
Emne: [bjornna/dips-ckm] Fjerne openEHR-EHR-OBSERVATION.temperature.v1.adl? (#5)


Arketypen openEHR-EHR-OBSERVATION.temperature.v1.adl er tiltenkt bruk på temperatur av et spesifikt objekt og IKKE kroppstemperatur.

This temperature is not to be used to record the body temperature, which is a surrogate for the whole body temperature of the subject - use OBSERVATION.body_temperature instead in this situation.

Det er viktig at disse ikke forveksles. Det har allerede skjedd og det er nok undertegnede som har tatt feil.

Skal vi fjerne denne arketypen fra repositoriet og heller legge den til når vi får behov?

**Comment by njamedar** [comment]
Høres lurt ut!
Nasrin

**Comment by bjornna** [comment]
Fjerner den nå.
